### PR TITLE
SilentContinue makes it hard to find issues

### PR DESCRIPTION
**Pull request by dominikheeb**
SilentContinue makes it hard to find issues. I would recommend to remove that or make it configurable

**Pull Request (PR) description**

**This Pull Request (PR) fixes the following issues:**

**Task list:**
- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated / added?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/126)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
@dominikheeb Is there a specific issue you are seeing that prompted this change? I would rather identify that rather than make a change here if we can help it. The reason I ask is that if we take the silentlycontinue off the new item command could see errors if the directory already exists instead of it moving on to the copy statement.  Happy to leave this one open to discuss it, but if there is an issue you are chasing we should raise it as an issue and work through it there first.

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by gaelcolas** [comment]
@dominikheeb what about leaving the `-SilentlyContinue` and adding `-ErrorVariable CopyItemsError` and showing verbose error message by iterating through `$CopyItemsError`?

**Comment by gaelcolas** [comment]
Closing for now. Let us know if you want to take it further.

**Pull request closed without merging**
