### PR TITLE
xVMHyperV: Redoing abondoned PRs

### LINKED ISSUE #145: xVMHyperV - Absent VM still tested for Vhd existence
Created a VHD -> **Disc1**
Created a VM -> **VM1**

Set VHD "**Disc1**" to 'Absent'
Set VM "**VM**1" to 'Absent

Everything ist removed, but you will get an error everytime the configuration is started/updated:

> PowerShell DSC-Ressource "MSFT_xVMHyperV" Function "Test-TargetResource"
> 
> Error: "Vhd 'C:\Hyper-V\Virtual Hard Disks\localhost-OSDisk.vhdx' does not exist."
>     + CategoryInfo          : InvalidOperation: (:) [], CimException
>     + FullyQualifiedErrorId : ProviderOperationExecutionFailure

I used the current release version on win10 - 1709

Test for "Absent" resources, should not be needed.

### LINKED ISSUE #149: xVMHyperV: Wrong localized string is used to throw error messages.
**Details of the scenario you tried and the problem that is occurring:**
This was reported in PR #148 by @Geogboe.

> `AutomaticCheckpointsUnsupportedError` on line 740 does not resolve to a defined localized data variable and it looks like it should be `AutomaticCheckpointsUnsupported` instead. Without this change a meaningless error message is produced: ScriptHalted instead of what is should be: `AutomaticCheckpoints are not supported on this host.`"

I think we should change the line 15 to 'AutomaticCheckpointsUnsupportedError' instead (the localized string is used at two locations).

https://github.com/PowerShell/xHyper-V/blob/834dec27c114783ed56b5f430f96fe1d1d6ea4e5/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L15

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by bgelens**
#### Pull Request (PR) description
* MSFT_xVMHyperV:
  * Moved localization string data to own file
  * Fixed code styling issues
  * Fixed bug where StartupMemory was not evaluated in Test-TargetResource
  * Redo of abandoned PRs
    * #148 
    * #67 
  * Fixed Get throws error when NetworkAdapters are not attached or missing properties

#### This Pull Request (PR) fixes the following issues

- Fixes #149 
- Fixes #145 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/163)

### CODE REVIEW

**Comment by bgelens** [comment]
@johlju, @PlagueHO Could you guys take a look at this? Trying to clean out some abandoned PRs and do some cleanup while I go

**Comment by PlagueHO** [comment]
I'll try and review this for you over the weekend @bgelens

**Comment by bgelens** [comment]
Thanks for the review @PlagueHO! Much appreciated 👍 

Are you ok with my reactions to your comments where I did not fix them in this PR?

**Comment by bgelens** [comment]
Thanks @PlagueHO!

**Pull request merged**
