### PR TITLE
xVMSwitch - Fixes #107 and adds comment based help and updates unit tests to latest template version

### LINKED ISSUE #107: xVMSwitch - Get-TargetResource throws when switch type is not external
Bug introduced by PR #96.
```Get-TargetResource``` doesn't take into account that it shouldn't query for ```NetAdapterInterfaceDescription(s)``` when switch type is Private or Internal

### LINKED ISSUE #108: xVMSwitch - Missing comment base help for Get, Set and Test-TargetResource

### PR DESCRIPTION
**Pull request by bgelens**
Fixes #108 
Fixes: #107

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/109)

### CODE REVIEW

**Comment by bgelens** [comment]
@PlagueHO could you review this PR please. Thanks!

**Comment by PlagueHO** [comment]
Hi @bgelens - great job! Just some minor style nitpicks in the tests - nothing that the correct settings in VS Code + applying auto formatting couldn't fix :grin:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 6 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-Knv9oMqcEEjcgMUYNnp:-Knv9oMqcEEjcgMUYNnq:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L6)):*
> ```PowerShell
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
> if ( (-not (Test-Path -Path (Join-Path -Path $script:moduleRoot -ChildPath 'DSCResource.Tests'))) -or `
>     (-not (Test-Path -Path (Join-Path -Path $script:moduleRoot -ChildPath 'DSCResource.Tests\TestHelper.psm1'))) ) {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 19 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-Knv9w6otWMwPMENU4_F:-Knv9w6otWMwPMENU4_G:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L19)):*
> ```PowerShell
> #endregion HEADER
> 
> function Invoke-TestSetup {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 22 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvA-xq_QXvMpCwYLNx:-KnvA-xq_QXvMpCwYLNy:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L22)):*
> ```PowerShell
> }
> 
> function Invoke-TestCleanup {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 27 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvA0WQLaEAQnCNXH2P:-KnvA0WRGfwTOyLvCwTy:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L27)):*
> ```PowerShell
> 
> # Begin Testing
> try {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 89 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvA3zmvGxVwqLawIkV:-KnvA3zmvGxVwqLawIkW:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L89)):*
> ```PowerShell
> 
>             # Create an empty function to be able to mock the missing Hyper-V cmdlet
>             function Get-VMSwitch { }
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 198 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-Knv9OpCkGwo9Cs5pUtX:-Knv9OpDX0iil17QeLrU:b9uywon) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L198)):*
> ```PowerShell
> 
>         Describe 'Validates Test-TargetResource Function' {
> ```

Nitpick: Should be no newline here - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 300 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAFvXBvGxYcb2CkOE:-KnvAFvXBvGxYcb2CkOF:bv4tp1u) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L300)):*
> ```PowerShell
>             function Set-VMSwitch { }
> 
>             # Mocks Get-VMSwitch and will return $global:mockedVMSwitch which is
> ```

Should be <# #> style for multi line comments

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 309 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAKWC-1YQUZqKgQ8F:-KnvAKWC-1YQUZqKgQ8G:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L309)):*
> ```PowerShell
>                 )
> 
>                 if ($ErrorAction -eq 'Stop' -and $global:mockedVMSwitch -eq $null) {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 337 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAQ8ZMY-ImeM_ry9K:-KnvAQ8ZMY-ImeM_ry9L:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L337)):*
> ```PowerShell
>                 )
> 
>                 if ($AllowManagementOS) {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 367 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvARlSph89ugCpItMI:-KnvARlSph89ugCpItMJ:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L367)):*
> ```PowerShell
>             # Create all the test cases for Get-TargetResource
>             $getTestCases = @()
>             foreach ($brmMode in $BANDWIDTH_RESERVATION_MODES) {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 6 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAZWE-gzvg_32LJtu:-KnvAZWE-gzvg_32LJtv:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L6)):*
> ```PowerShell
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
> if ( (-not (Test-Path -Path (Join-Path -Path $script:moduleRoot -ChildPath 'DSCResource.Tests'))) -or `
>     (-not (Test-Path -Path (Join-Path -Path $script:moduleRoot -ChildPath 'DSCResource.Tests\TestHelper.psm1'))) ) {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 19 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAavhm8iJctn0fxO-:-KnvAaviYtbwO0v40egB:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L19)):*
> ```PowerShell
> #endregion HEADER
> 
> function Invoke-TestSetup {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 22 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAa9S4EDIWRBoVTs3:-KnvAa9S4EDIWRBoVTs4:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L22)):*
> ```PowerShell
> }
> 
> function Invoke-TestCleanup {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 27 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAcIAv66YF1ieDd3n:-KnvAcIBKEBXay3AAHvU:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L27)):*
> ```PowerShell
> 
> # Begin Testing
> try {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 33 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAbgEfYdPAM9GOTEi:-KnvAbgEfYdPAM9GOTEj:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L33)):*
> ```PowerShell
> 
>         # Function to create a exception object for testing output exceptions
>         function Get-InvalidArgumentError {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 123 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAdARxIKGBpOa9EvG:-KnvAdASaNYAuPnNCHXo:b-wlr5op) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L123)):*
> ```PowerShell
>                 )
> 
>                 if ($ErrorAction -eq 'Stop' -and $global:mockedVMSwitch -eq $null) {
> ```

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 413 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAeZuYclzqRrpZiSZ:-KnvAeZuYclzqRrpZiS_:b31iecj) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L413)):*
> ```PowerShell
>         }
>     }
> } finally {
> ```

Nitpick: } and { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-:-KnvAkV4dUE9pkbXuOVT:b-kdxoe4)*

**Comment by bgelens** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 6 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-Knv9oMqcEEjcgMUYNnp:-KnvCNzi28JGZycaiZ43:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L6)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 19 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-Knv9w6otWMwPMENU4_F:-KnvCZimrtb_Dk5A91oF:b-896fiz) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L19)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done,

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 22 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvA-xq_QXvMpCwYLNx:-KnvDFOKxrMh8e-QiGiM:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L22)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 27 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvA0WQLaEAQnCNXH2P:-KnvDGJkS-fzUVF8wucs:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L27)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 89 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvA3zmvGxVwqLawIkV:-KnvMk4Xnr7ahFvI-2v3:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L89)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 198 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-Knv9OpCkGwo9Cs5pUtX:-KnvG4_Ci2kPuilJZdBb:bgjjcp) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L198)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: Should be no newline here - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Can't do that with describe

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 300 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAFvXBvGxYcb2CkOE:-KnvGt8AbeCzdaE3obr1:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L300)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be <# #> style for multi line comments
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 309 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAKWC-1YQUZqKgQ8F:-KnvGvINJblZIJXRN3oX:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L309)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 337 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAQ8ZMY-ImeM_ry9K:-KnvGx9mB-LVWEg6x7oU:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L337)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 367 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvARlSph89ugCpItMI:-KnvGypV7g-SO53lVPmP:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L367)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 6 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAZWE-gzvg_32LJtu:-KnvLpJxQsOMXP0OKdVw:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L6)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 19 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAavhm8iJctn0fxO-:-KnvLsMS3fLV3mcEAON1:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L19)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 22 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAa9S4EDIWRBoVTs3:-KnvLthPVQhDKLRG3Wsv:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L22)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 27 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAcIAv66YF1ieDd3n:-KnvLwxphNHtY0OUxL4R:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L27)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 33 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAbgEfYdPAM9GOTEi:-KnvLyNJvbErFp55Jvcn:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L33)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 123 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAdARxIKGBpOa9EvG:-KnvM4q9Lxnl5qnRslRv:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L123)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 413 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvAeZuYclzqRrpZiSZ:-KnvM6GXFx2cZV0CxkVH:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L413)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: } and { Should be on next line - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/109)*

**Comment by PlagueHO** [comment]
Just a couple of missed ones. Sorry! But looking great.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 198 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-Knv9OpCkGwo9Cs5pUtX:-KnvSP5DG2bK47yeaSbr:b2qvz06) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L198)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

Can't do that with describe
</blockquote></details>

What I meant was that there should _not_ be empty line here :grin: E.g.
```powershell
Describe 'Validates Test-TargetResource Function' {
  # Create an empty function to be able to mock the missing Hyper-V cmdlet
```

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 108 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvSukVrfqI_vj8KUg5:-KnvSukWmN_IYbGLdM5q:bt0xsiy) ([raw file](https://github.com/powershell/xhyper-v/blob/9c017832e6f7bcd556dbed4a995e271cc2777573/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L108)):*
> ```PowerShell
>             }
> 
>             function Set-VMSwitch {
> ```

Missed this one.

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 112 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvSwUA_sWb8C8xUytG:-KnvSwUA_sWb8C8xUytH:bt0xsiy) ([raw file](https://github.com/powershell/xhyper-v/blob/9c017832e6f7bcd556dbed4a995e271cc2777573/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L112)):*
> ```PowerShell
>             }
> 
>             function Remove-VMSwitch {
> ```

Missed this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-:-KnvSzc6pnnW2oTng2JS:b7bnf7w)*

**Comment by bgelens** [comment]
Thanks @PlagueHO! I think this is it :smile:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1, line 198 at r1](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-Knv9OpCkGwo9Cs5pUtX:-Knwmr9BVYffwVTZ42BO:b-m11sfj) ([raw file](https://github.com/powershell/xhyper-v/blob/a9b2242c553089ead21e5bb69cb1bd9f249b5b89/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L198)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

What I meant was that there should _not_ be empty line here :grin: E.g.
```powershell
Describe 'Validates Test-TargetResource Function' {
  # Create an empty function to be able to mock the missing Hyper-V cmdlet
```
</blockquote></details>

I see :) Done (and in other places as well)

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 108 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvSukVrfqI_vj8KUg5:-Knwn9rIpNv1G-enJ2Sl:b-896fix) ([raw file](https://github.com/powershell/xhyper-v/blob/9c017832e6f7bcd556dbed4a995e271cc2777573/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L108)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Missed this one.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1, line 112 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-KnvSwUA_sWb8C8xUytG:-KnwnAahqLa54yNf_nYi:b-896fix) ([raw file](https://github.com/powershell/xhyper-v/blob/9c017832e6f7bcd556dbed4a995e271cc2777573/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L112)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Missed this one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-:-Knwn_1QxGzzCwVuGvSf:b-3r0iy2)*

**Comment by PlagueHO** [comment]
Thanks @Bgelens

:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/109#-:-KnxaOddTSe6LtwIEBTd:b4zzr8u)*

**Pull request merged**
