### PR TITLE
Fixing 'generation' properties values. Fixes #36

### LINKED ISSUE #36: Wrong value for 'Generation' field in Examples
Install xHyper-V module version 3.2.0.0 from PSGallery. In some examples (e.g. Sample_xVMHyperV_Complete) we have:
# Ensures a VM with all the properties

xVMHyperV NewVM
{
    Ensure          = 'Present'
    Name            = $VMName
    VhdPath         = $VhdPath
    SwitchName      = $SwitchName
    State           = $State
    Path            = $Path
    Generation      = $VhdPath.Split('.')[-1]
    StartupMemory   = $StartupMemory
    MinimumMemory   = $MinimumMemory
    MaximumMemory   = $MaximumMemory
    ProcessorCount  = $ProcessorCount
    MACAddress      = $MACAddress
    RestartIfNeeded = $true
    WaitForIP       = $WaitForIP 
    DependsOn       = '[WindowsFeature]HyperV'
}

But the schema has:

[ClassVersion("1.0.0"), FriendlyName("xVMHyperV")]
class MSFT_xVMHyperV : OMI_BaseResource
{
 ...
    [Write, Description("Virtual machine generation")] Uint32 Generation;
...
};

I think previous versions had something similar to schema for xVHD:

[ClassVersion("1.0.0"), FriendlyName("xVHD")]
class MSFT_xVHD : OMI_BaseResource
{
...
    [Write, Description("Virtual disk format - Vhd or Vhdx"), ValueMap{"Vhd","Vhdx"}, Values{"Vhd","Vhdx"}] String Generation;
...
};

### PR DESCRIPTION
**Pull request by zjalali**
Just updating examples addressing issue #36 .

### CODE REVIEW

**Comment by KarolKaczmarek** [comment]
Thanks @zjalali 
Could you please update readme.md with description of your changes as described here: https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#lifecycle-of-a-pull-request
Thanks!

**Comment by TravisEz13** [comment]
If there is no update of the pull request within 7 days, we will close the pull request.  After that, if you have an update, feel free to reopen the pull request or a new pull request.

**Comment by TravisEz13** [comment]
Please resolve merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )

**Comment by zjalali** [comment]
@TravisEz13  @KarolKaczmarek This is ready for a final review.

**Comment by HemantMahawar** [comment]
@zjalali  what's the change in schema file (MSFT_xVMHyperV.schema.mof)? The change list shows that file as well.

**Comment by zjalali** [comment]
@HemantMahawar Not sure why that file is included in the change since I don't see any actual changes in there. I will take a look.

**Comment by zjalali** [comment]
@KarolKaczmarek we can close this PR.

**Comment by TravisEz13** [comment]
closed per comment

**Pull request closed without merging**
