### PR TITLE
xHyper-V - Fixes to Examples

### PR DESCRIPTION
**Pull request by Chirishman**
**Pull Request (PR) description**

- Changed all references to `$vhdPath` where used as a static variable to $sampleVhdPath to remove confusion with named configuration parameters.
- Replaced all uses of the parameter `$baseVhdPath` with references to `$vhdPath` for clarity

**This Pull Request (PR) fixes the following issues:**

- Potential confusion between named parameters and variable containing sample value
- Identical value represented with different parameter name between examples
- `$vhdPath` is not defined within the scope of the `Sample_EndToEndXHyperV_RunningVM` configuration

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/133)

### CODE REVIEW

**Comment by Chirishman** [comment]
Build fails are on unmodified files that do not reference the modified example file.

**Comment by Chirishman** [comment]
@PlagueHO I just saw your request to be tagged in here (this is the more minor of the two)

**Comment by BrianFarnhill** [comment]
@Chirishman  Can I get you to do a pull from the dev branch to get the tests to pass (I just merged a fix in there for it). I'll get through the review of this one after that.

**Comment by Chirishman** [comment]
@BrianFarnhill Done

**Comment by PlagueHO** [comment]
Thanks @Chirishman ! Looks like @BrianFarnhill is back on deck anyway! :grin: @BrianFarnhill - I wasn't sure you were the repo maintainer for this one either - but assumed you picked it up because no one else had.

**Comment by BrianFarnhill** [comment]
@PlagueHO I'm happy to keep it warm until someone else steps up. You looking to add another module to your list? ;-)

**Comment by PlagueHO** [comment]
Hahaha @BrianFarnhill :grin: but yes, I plan to pick this one up once I've finished the move of xComputerManagement to HQRM (nearly there). I'll wait till next year thought right :wink:

**Comment by BrianFarnhill** [comment]
:lgtm: but will just need a merge from PowerShell/dev to resolve conflicts. Happy with the way the rest of it looks though.

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/133#-:-L0koDDN_BxrBzzvqvJB:brr7vpk)*

**Comment by Chirishman** [comment]
Conflicts resolved, should be good to go!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/133#-:-L0ttdkl1Xvlf_eYVovi:b-m403e1)*

**Pull request merged**
