### PR TITLE
xVMHyperV - Added support for AutomaticCheckpointsEnabled

### LINKED ISSUE #130: Disable Hyper-V Automatic Checkpoints
In the latest Win 10 1709 update, automatic checkpoints are enabled by default.

image

Unfortunately, it looks like there is no global setting to configure this and it is controlled on a per-VM basis, Therefore, I think this will need to be implemented on the xVMHyperV resource.

### PR DESCRIPTION
**Pull request by SimonWahlin**
**Pull Request (PR) description**
Adds support for AutomaticCheckpoints of VMs as described in #130 

**This Pull Request (PR) fixes the following issues:**
Fixes #130

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated / added?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/131)

### CODE REVIEW

**Comment by SimonWahlin** [comment]
Submitted a PR for this even if it isn't 100% complete yet, hope that is OK.

I'll complete that task list as soon as I have a little time again, any feedback on the code changes are greatly appreciated.

**Comment by SimonWahlin** [comment]
If I've understod the contribution requirements correctly this should be ready for review.

Took the liberty to expand the Sample_xVMHyperV_Complete.ps1 to actually create a complete VM by also creating the required VHD.

**Comment by BrianFarnhill** [comment]
@SimonWahlin  Can I get you to have a look at the failing unit tests and resolve the merge conflicts on this one? I'll review it after that.

**Comment by BrianFarnhill** [comment]
@SimonWahlin  OK you should be able to do a pull from the dev branch now and get something that will fix the tests. Once that's all green I'll do a review of it all

**Comment by SimonWahlin** [comment]
Thank you @BrianFarnhill I've merged the upstream commits now.

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/131#-:-L0kn1rlqq9F8P5e0Fkh:bnfp4nl)*

**Pull request merged**
