### PR TITLE
Fixes VM Power State Issue

### LINKED ISSUE #6: Enforced VM Power State
The current implement of the xVMHyper-V resource enforces that a VM is in a particular power state. If no state is specified then it's powered off!

I think that this is incorrect behaviour as it will turn off VMs __unless__ you explicitly state you want VMs running __all__ the time. In a lab/dev/test (or maybe even a production) environment, you might want to ensure that VMs are provisioned in a particular way, but managing the power state is not always desirable (pun intended!).

I think this should be the behaviour:

* If the configuration document specifies a State of 'Off', 'Running' or 'Paused' then this should be enforced.
* If the configuration document does not specify a State, then no change to the VM should be made.

### PR DESCRIPTION
**Pull request by iainbrighton**
OK - second attempt!

* Fixes #6
* Removed default 'Off' setting from the xVMHyper-V $State property
* Added check for $State property being set before calling Set-VMState
* Added Pester tests

### CODE REVIEW

**Comment by iainbrighton** [comment]
[SIGH] Need to create empty functions so I can mock the Hyper-V cmdlets to get the tests passing.

**Comment by vors** [comment]
Maybe [`-ModuleName`](https://github.com/pester/Pester/wiki/Unit-Testing-within-Modules) would work?

**Comment by iainbrighton** [comment]
Unfortunately I don't think that'll work. Pester will only mock commands that it can find. I'll need to get this on machine without the Hyper-V cmdlets installed and do some more testing..

**Comment by iainbrighton** [comment]
Finally! \o/

**Comment by TravisEz13** [comment]
Looks good, thanks for the contribution.

**Pull request merged**
