### PR TITLE
xVMSwitchFeature - load balancing algorithm parameter for SET Switch

### LINKED ISSUE #138: Feature Request: VMSwitchTeam LoadBalancingAlgorithm
We need to set `LoadBalancingAlgorithm`  (as in `Set-VMSwitchTeam -Name "SwitchName" -LoadBalancingAlgorithm hypervport`) to hypervport port in our environment.  Dynamic mode results in dropped packets.  Can this be configured as part of xVMSwitch?  If not, can this be a feature request?

### PR DESCRIPTION
**Pull request by J0F3**
**Pull Request (PR) description**
Added new parameter to specify the load balancing algorithm when Switch Embedded Teaming (SET) is used.

**This Pull Request (PR) fixes the following issues:**
Fixes #138

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated / added?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/142)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Thanks for the submission @J0F3  - I'll review this as soon as I am able. In the meantime though can I get you to do a pull from upstream to resolve the merge conflict on the changelog? Thanks

**Comment by J0F3** [comment]
@BrianFarnhill 
Sure. No problem I have just done that and I have resolved the merge conflict on the changelog. Thx!

**Comment by BrianFarnhill** [comment]
One tiny little change (to the point where I feel bad for calling it out) and the rest looks amazing. A quick update and we can merge this one in.

---

Reviewed 3 of 7 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.psm1, line 72 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/142#-L3PVLdlYpyiR5kzzmNA:-L3PVLdlYpyiR5kzzmNB:b-bavzh5) ([raw file](https://github.com/powershell/xhyper-v/blob/d6d090c785caaa487b09d3be58cb318cc3221310/DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.psm1#L72)):*
> ```PowerShell
>                 $description = $switch.NetAdapterInterfaceDescription
> 
>                 $loadBalancingAlgorithm = 'N/A'
> ```

Can we change the value to 'NA' (without the slash) to line up with how other attributes on this resource do it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/142#-:-L3PW6xFGk7NunGIhyZU:b-h7z40z)*

**Comment by J0F3** [comment]
Thanks for checking my changes!
No problem, I have just changed the value to 'NA'. Makes absolute sense. 👍

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/142#-:-L3V2M3h-8hH8sLzf4Nx:bnfp4nl)*

**Pull request merged**
