### PR TITLE
EnableGuestService localized OS fix 3

### PR DESCRIPTION
**Pull request by vrdse**
Fix for #76

Thanks @joeyaiello for your help at #83. I did not succeed on the rebase, as the conflicts where to complicated. But I simply made the few required changes to the latest code base. I hope all issues are now solved.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/91)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @vrdse - great job on the fix! Are you able to add an entry to the README.MD (see https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#update-the-release-notes)?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/91#-:-KjUXJnp5glXZnfzdT_I:b-oggflp)*

**Comment by vrdse** [comment]
@PlagueHO sure, release notes are added

**Comment by PlagueHO** [comment]
:lgtm:

Thanks @vrdse

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/91#-:-KjarSfaEI_9BZDgX2N7:bhgodgg)*

**Comment by bgelens** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 71 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/91#-KmLPgZwa_80i_WweOF0:-KmLPgZwa_80i_WweOF1:berxbuz) ([raw file](https://github.com/powershell/xhyper-v/blob/69ef24b6543a8002f65293a25ac69836a60ebd08/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L71)):*
> ```PowerShell
>     } 
> 
>     $GuestServiceRegex = "Microsoft:[0-9A-Fa-f]{8}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{12}\\6C09BB55-D683-4DA0-8931-C9BF705F6480"
> ```

I'm not sure why you want to use regex for this? I think it would be more readable / understandable for others if this was an explicit ```-eq``` instead of ```-Match```.

```powershell
$GuestServiceId = 'Microsoft:E02677CA-C259-4618-8933-11543D149290\6C09BB55-D683-4DA0-8931-C9BF705F6480'
EnableGuestService = ($vmobj | Get-VMIntegrationService | Where-Object  -FilterScript {$_.Id -eq $GuestServiceId}).Enabled
```

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 96 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/91#-KmLOQ5Ytgx95XLhMXal:-KmLOQ5Ytgx95XLhMXam:bdapcim) ([raw file](https://github.com/powershell/xhyper-v/blob/69ef24b6543a8002f65293a25ac69836a60ebd08/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L96)):*
> Fa-f]{8}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{12}\\6C09BB55-D683-4DA0-8931-C9BF705F6480"
I'm not sure why you want to use regex for this? I think it would be more readable / understandable for others if this was an explicit ```-eq``` instead of ```-Match```.

```powershell
$GuestServiceId = 'Microsoft:E02677CA-C259-4618-8933-11543D149290\6C09BB55-D683-4DA0-8931-C9BF705F6480'
EnableGuestService = ($vmobj | Get-VMIntegrationService | Where-Object  -FilterScript {$_.Id -eq $GuestServiceId}).Enabled
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/91)*

**Comment by vrdse** [comment]
@bgelens the ID consits of Microsoft:VMId\IntegrationServiceId, i.e. the full ID is not static. The VMId is a GUID that is unique for each VM and the RegEx represents a valid GUID.

As an alternative to the RegEx, I could first obtain the VMid, build the full IntegrationServiceId and filter for that with -eq.

`$VMId = ($vmobj).Id
$GuestServiceId = "Microsoft:$VMId\6C09BB55-D683-4DA0-8931-C9BF705F6480"
EnableGuestService = ($vmobj | Get-VMIntegrationService | Where-Object  -FilterScript {$_.Id -eq $GuestServiceId}).Enabled
`
Would you prefer it that way?

**Comment by bgelens** [comment]
I see, thanks for pointing that out!
For readability I would prefer your alternate suggestion over the regex.  That way you won't have people wondering what the regex is doing but instead see from your 'simpler' code what is going on immediately.

If you want to put in the effort, please do! Thanks!

**Comment by vrdse** [comment]
@bgelens No worries at all, I just pushed a new commit. Please review the changes.

**Comment by bgelens** [comment]
Thanks! Could you update the Reviewable. Just say done at my comments so I can check them off. I'll merge this after

**Comment by vrdse** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 71 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/91#-KmLPgZwa_80i_WweOF0:-KmSlAEBpzZTY2Vre72x:bb7f2mf) ([raw file](https://github.com/powershell/xhyper-v/blob/69ef24b6543a8002f65293a25ac69836a60ebd08/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L71)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

I'm not sure why you want to use regex for this? I think it would be more readable / understandable for others if this was an explicit ```-eq``` instead of ```-Match```.

```powershell
$GuestServiceId = 'Microsoft:E02677CA-C259-4618-8933-11543D149290\6C09BB55-D683-4DA0-8931-C9BF705F6480'
EnableGuestService = ($vmobj | Get-VMIntegrationService | Where-Object  -FilterScript {$_.Id -eq $GuestServiceId}).Enabled
```
</blockquote></details>

done

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 96 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/91#-KmLOQ5Ytgx95XLhMXal:-KmSlCU4vgac7ZAiJb03:bb7f2mf) ([raw file](https://github.com/powershell/xhyper-v/blob/69ef24b6543a8002f65293a25ac69836a60ebd08/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L96)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

> Fa-f]{8}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{12}\\6C09BB55-D683-4DA0-8931-C9BF705F6480"
I'm not sure why you want to use regex for this? I think it would be more readable / understandable for others if this was an explicit ```-eq``` instead of ```-Match```.

```powershell
$GuestServiceId = 'Microsoft:E02677CA-C259-4618-8933-11543D149290\6C09BB55-D683-4DA0-8931-C9BF705F6480'
EnableGuestService = ($vmobj | Get-VMIntegrationService | Where-Object  -FilterScript {$_.Id -eq $GuestServiceId}).Enabled
```
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/91)*

**Comment by bgelens** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 71 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/91#-KmLPgZwa_80i_WweOF0:-KmSh58EBYbrPkSRONIP:bb6ywmx) ([raw file](https://github.com/powershell/xhyper-v/blob/69ef24b6543a8002f65293a25ac69836a60ebd08/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L71)):*
<details><summary><i>Previously, vrdse wrote…</i></summary><blockquote>

done
</blockquote></details>

LGTM

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 96 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/91#-KmLOQ5Ytgx95XLhMXal:-KmShFgSBlIQ7Kc8iIjc:bb6ywmx) ([raw file](https://github.com/powershell/xhyper-v/blob/69ef24b6543a8002f65293a25ac69836a60ebd08/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L96)):*
<details><summary><i>Previously, vrdse wrote…</i></summary><blockquote>

done
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/91#-:-KmSmBTNQhrdhi4o39mD:bnfp4nl)*

**Comment by bgelens** [comment]
Thank you! 👍

**Pull request merged**
