### PR TITLE
Increase xVMHyperV VM guest StartupMemory max limit and MinimumMemory max limit from 17GB to 64GB

### PR DESCRIPTION
**Pull request by MnrGreg**
Fixes [#93](https://github.com/PowerShell/xHyper-V/issues/93)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/94)

### CODE REVIEW

**Comment by iainbrighton** [comment]
@MnrGreg I'm not sure why the maximum was set at 16GB? Can you update the documentation and add a line in the README.md with your change?

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/94#-:-KkPN90awe0igkNhwCGg:bnfp4nl)*

**Comment by bgelens** [comment]
I think all the memory properties need to be reviewed. Gen 1 VM max memory is 1TB but Gen 2 VM is 12 TB according to [2016 scalability guide](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-for-hyper-v-scalability-in-windows-server-2016)

The resource current maximum is 1048576MB which is the 1TB limit for Gen1.

I don't know where / when the validateset on Startup, Minimum and Maximum where established but I think they need to be adjusted to the most modern limits. Could you update them all with regards to most up 2 date values?

**Comment by iainbrighton** [comment]
@bgelens Yes, but the 2008 R2 Gen 1 maximum is 64GB. Therefore, I think we have two options:

1. We set the maximum to 64GB to maintain full compatibility across all hosts.
2. If we want to support both 2008R2 and 2012 (and later) maximums, we need to drop the `[ValidateRange()]` and implement that functionality separately. 

If we wanted to support Gen 2 maximums, the second option also makes sense. Thoughts?

**Comment by bgelens** [comment]
@iainbrighton I don't think it's a good idea to constraint users on newer OSes from using this resource (although, probably not many VMs with these huge sizes will be created by this resource. But can't assume right! ;) ). 

I think your suggested option 2 is the desired option and put in some validate logic based on OS and limits in the functions. To make this clear to the end-user, the readme should be updated to explain that the behavior is a per platform version limit and the description in the schema should make users aware as well.

Other thoughts? @dscottraynsford @MnrGreg

**Comment by iainbrighton** [comment]
I would be inclined to set the limits as per option 1 now, and then open another issue to implement option 2?

**Comment by bgelens** [comment]
@iainbrighton Created a new issue as you suggest #102 
In this PR we go with the upper limit of 2008R2 of 64GB for startup and minimum memory.

@MnrGreg could you make this PR editable by maintainers by checking the box on the right side? Or fix the merge conflict in the README please. Thanks!

**Comment by MnrGreg** [comment]
@iainbrighton moved README comment to Unreleased section and allowing edits from Maintainers. thanks

**Comment by PlagueHO** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 131 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/94#-Kme_zR7qMxivu0x4ynu:-Kme_zR7qMxivu0x4ynv:b-bti3fz) ([raw file](https://github.com/powershell/xhyper-v/blob/52618c848167dbd524fea1590d6aec1b8ab1fc99/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L131)):*
> ```PowerShell
> 
>         # Startup RAM for the VM
>         [ValidateRange(32MB,65536MB)]
> ```

All these parameters need to be adjusted to match style guidelines:
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block

E.g.
```powershell
[Parameter()]
[ValidateRange(32MB,65536MB)]
[Uint64]
$StartupMemory
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/94)*

**Comment by bgelens** [comment]
:lgtm: I'll merge this once #100 is merged

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 131 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/94#-Kme_zR7qMxivu0x4ynu:-Kmh83SgSJEhlmvVBO1W:b-xwinso) ([raw file](https://github.com/powershell/xhyper-v/blob/52618c848167dbd524fea1590d6aec1b8ab1fc99/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L131)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

All these parameters need to be adjusted to match style guidelines:
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block

E.g.
```powershell
[Parameter()]
[ValidateRange(32MB,65536MB)]
[Uint64]
$StartupMemory
```

</blockquote></details>

FYI I'll fix these in a later commit. Raised #104 to track

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/94#-:-Kmh9AlhqQEKv8_9PNXY:b-fefgbc)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 131 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/94#-Kme_zR7qMxivu0x4ynu:-KmjZHCBSExeHBZgM_X3:bhq7aep) ([raw file](https://github.com/powershell/xhyper-v/blob/52618c848167dbd524fea1590d6aec1b8ab1fc99/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L131)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

FYI I'll fix these in a later commit. Raised #104 to track
</blockquote></details>

All good! I just thought I'd mention it :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/94#-:-KmjZPAGQh1Nd2i2Dm3N:bnfp4nl)*

**Pull request merged**
