### PR TITLE
fixes issues introduced with PR #91

### PR DESCRIPTION
**Pull request by bgelens**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/100)

### CODE REVIEW

**Comment by bgelens** [comment]
@iainbrighton Could you review this please. This PR contains fixes for issues missed in review of #91.

**Comment by PlagueHO** [comment]
Great job @bgelens - sorry about the nitpicks in existing code. I know you didn't actually change this code in the PR, but it can help for future to fix style problems when we see them.

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 98 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_fvh9Twb6191gxpnm:-Km_fvh9Twb6191gxpnn:bflzzeb) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L98)):*
> ```PowerShell
>         HasDynamicMemory   = $vmobj.DynamicMemoryEnabled
>         NetworkAdapters    = $vmobj.NetworkAdapters.IPAddresses
>         EnableGuestService = ($vmobj | Get-VMIntegrationService | Where-Object {$_.Id -eq $guestServiceId}).Enabled
> ```

Where-Object has a positional parameter - should use named parameter. E.g.
`Where-Object -FilterScript { ...`

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 314 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_fsysPD-FL7kMv21l:-Km_fsysPD-FL7kMv21m:bd3x4nw) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L314)):*
> ```PowerShell
>             }
> 
>             #If the VM doesn't have Guest Service Interface correctly configured, update it.
> ```

Needs a space between # and If

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 318 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_g8ViYSGzLO99VS6S:-Km_g8ViYSGzLO99VS6T:bflzzeb) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L318)):*
> ```PowerShell
>             $guestServiceId = "Microsoft:$vmId\6C09BB55-D683-4DA0-8931-C9BF705F6480"
> 
>             $GuestService = $vmObj | Get-VMIntegrationService | Where-Object {$_.Id -eq $guestServiceId}
> ```

Where-Object has a positional parameter - should use named parameter. E.g.
`Where-Object -FilterScript { ...`

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 414 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_gBjKP2JBJYu3k3iu:-Km_gBjKP2JBJYu3k3iv:bflzzeb) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L414)):*
> ```PowerShell
>                 $vmId = (Get-VM -Name $Name).Id
>                 $guestServiceId = "Microsoft:$vmId\6C09BB55-D683-4DA0-8931-C9BF705F6480"
>                 Get-VMIntegrationService -VMName $Name | Where-Object {$_.Id -eq $guestServiceId} | Enable-VMIntegrationService
> ```

Where-Object has a positional parameter - should use named parameter. E.g.
`Where-Object -FilterScript { ...`

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 597 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_gDkb0DLJUlAem88H:-Km_gDkcoClJ0OimcgXU:bflzzeb) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L597)):*
> ```PowerShell
>             $vmId = $vmObj.Id
>             $guestServiceId = "Microsoft:$vmId\6C09BB55-D683-4DA0-8931-C9BF705F6480"
>             if (($vmObj | Get-VMIntegrationService | Where-Object {$_.Id -eq $guestServiceId}).Enabled -ne $EnableGuestService)
> ```

Where-Object has a positional parameter - should use named parameter. E.g.
`Where-Object -FilterScript { ...`

---

*[Tests/Unit/MSFT_xVMHyperV.Tests.ps1, line 67 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_gNasmtGqmhU3MKvy:-Km_gNasmtGqmhU3MKvz:b-3tty0k) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/Tests/Unit/MSFT_xVMHyperV.Tests.ps1#L67)):*
> ```PowerShell
>             Notes = '';
>         }
>         $stubGuestServiceInterfaceId = 'Microsoft:' + $stubVM.ID + '\6C09BB55-D683-4DA0-8931-C9BF705F6480'
> ```

Not a requirement, just a suggestion: String concat is quite slow. Suggest using `"Microsoft:$($stubVM.ID)\6C09BB55-D683-4DA0-8931-C9BF705F6480"` or -f or StringBuilder. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-:-Km_h2Dr1lJuiV7zb1PG:bcflid9)*

**Comment by bgelens** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 98 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_fvh9Twb6191gxpnm:-Km_kTviIyauVRCqvjYW:bl3rx35) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L98)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Where-Object has a positional parameter - should use named parameter. E.g.
`Where-Object -FilterScript { ...`
</blockquote></details>

Added named param

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 314 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_fsysPD-FL7kMv21l:-Km_kTAdY1RAsA2aIqCR:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L314)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Needs a space between # and If
</blockquote></details>

Done

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 318 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_g8ViYSGzLO99VS6S:-Km_kSMPnPQWfKFX7JtM:bl3rx35) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L318)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Where-Object has a positional parameter - should use named parameter. E.g.
`Where-Object -FilterScript { ...`
</blockquote></details>

Added named param

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 414 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_gBjKP2JBJYu3k3iu:-Km_kRVsi6OvJxe-aBpx:bl3rx35) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L414)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Where-Object has a positional parameter - should use named parameter. E.g.
`Where-Object -FilterScript { ...`
</blockquote></details>

Added named param

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 597 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_gDkb0DLJUlAem88H:-Km_kPoOKCEf8GhCk4Op:bl3rx35) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L597)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Where-Object has a positional parameter - should use named parameter. E.g.
`Where-Object -FilterScript { ...`
</blockquote></details>

Added named param

---

*[Tests/Unit/MSFT_xVMHyperV.Tests.ps1, line 67 at r2](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Km_gNasmtGqmhU3MKvy:-Km_kNlVUEQAWXoVuNwH:bam2mku) ([raw file](https://github.com/powershell/xhyper-v/blob/5cd9c801b82e4a31b56109e34affff649b1ec38b/Tests/Unit/MSFT_xVMHyperV.Tests.ps1#L67)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Not a requirement, just a suggestion: String concat is quite slow. Suggest using `"Microsoft:$($stubVM.ID)\6C09BB55-D683-4DA0-8931-C9BF705F6480"` or -f or StringBuilder. 
</blockquote></details>

Done using -f

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/100)*

**Comment by PlagueHO** [comment]
Great stuff @bgelens! So good to have you working on all this.

:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-:-Km_vGpHtBVnk8APiDHY:b-8emb1x)*

**Comment by iainbrighton** [comment]
@bgelens - just a couple of minor things and then I think we're done :wink: 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 318 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-KmesQG2HMkenXdoT77Z:-KmesQG2HMkenXdoT77_:b4nuxoj) ([raw file](https://github.com/powershell/xhyper-v/blob/14dc7c2db866dae1870b86896c396f0bc536927e/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L318)):*
> ```PowerShell
>             $guestServiceId = "Microsoft:$vmId\6C09BB55-D683-4DA0-8931-C9BF705F6480"
> 
>             $GuestService = $vmObj | Get-VMIntegrationService | Where-Object -FilterScript {$_.Id -eq $guestServiceId}
> ```

`$guestService` and not `$GuestService`

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 319 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Kmesj8wS6MiK5JgZb9n:-Kmesj8xH0HL1WchdfHM:bdqq6t8) ([raw file](https://github.com/powershell/xhyper-v/blob/14dc7c2db866dae1870b86896c396f0bc536927e/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L319)):*
> ```PowerShell
> 
>             $GuestService = $vmObj | Get-VMIntegrationService | Where-Object -FilterScript {$_.Id -eq $guestServiceId}
>             if ($GuestService.Enabled -eq $false -and $EnableGuestService)
> ```

$guestService

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 321 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-KmeslQotI5sUNVTsqlt:-KmeslQotI5sUNVTsqlu:bkgnkik) ([raw file](https://github.com/powershell/xhyper-v/blob/14dc7c2db866dae1870b86896c396f0bc536927e/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L321)):*
> ```PowerShell
>             if ($GuestService.Enabled -eq $false -and $EnableGuestService)
>             {
>                 Write-Verbose -Message ($localizedData.VMPropertyShouldBe -f 'EnableGuestService', $EnableGuestService, $GuestService.Enabled)
> ```

$guestService - I think you get the idea :wink: 

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 598 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Kmg7SeNQBe65HYz2q7j:-Kmg7SeNQBe65HYz2q7k:b-8ee6gk) ([raw file](https://github.com/powershell/xhyper-v/blob/14dc7c2db866dae1870b86896c396f0bc536927e/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L598)):*
> ```PowerShell
>             $guestServiceId = "Microsoft:$vmId\6C09BB55-D683-4DA0-8931-C9BF705F6480"
>             if (($vmObj | Get-VMIntegrationService | Where-Object -FilterScript {$_.Id -eq $guestServiceId}).Enabled -ne $EnableGuestService)
>             {
> ```

Don't we want a `Write-Verbose -Message ($localizedData.VMPropertyShouldBe ..)` statement showing why the method is returning $false?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-:-Kmg7khm2Ad-wMnC6HhW:b-45a90g)*

**Comment by bgelens** [comment]
Thanks @iainbrighton!! Done. I also noticed guestServiceId was sometimes created using concat, subexp or string format. Unified all to string format

---

Reviewed 1 of 2 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 318 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-KmesQG2HMkenXdoT77Z:-Kmgy6bxPHhU6d3CEErn:bcp4f4x) ([raw file](https://github.com/powershell/xhyper-v/blob/14dc7c2db866dae1870b86896c396f0bc536927e/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L318)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary><blockquote>

`$guestService` and not `$GuestService`
</blockquote></details>

darn it, missed those in earlier commit. Thanks! and done!

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 319 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Kmesj8wS6MiK5JgZb9n:-Kmgz20mfxIMVN3FYrE9:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/14dc7c2db866dae1870b86896c396f0bc536927e/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L319)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary><blockquote>

$guestService
</blockquote></details>

Done

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 321 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-KmeslQotI5sUNVTsqlt:-Kmgz2rIr-FdvZopUOqJ:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/14dc7c2db866dae1870b86896c396f0bc536927e/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L321)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary><blockquote>

$guestService - I think you get the idea :wink: 
</blockquote></details>

Done

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 598 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-Kmg7SeNQBe65HYz2q7j:-Kmh3Vb95uuuHzL9Ntgx:bb6un1j) ([raw file](https://github.com/powershell/xhyper-v/blob/14dc7c2db866dae1870b86896c396f0bc536927e/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L598)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary><blockquote>

Don't we want a `Write-Verbose -Message ($localizedData.VMPropertyShouldBe ..)` statement showing why the method is returning $false?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-:-Kmh3b-35CRQ4ntWIDCT:b-hp7ph3)*

**Comment by bgelens** [comment]
Had to push again as appveyor didn't start

**Comment by iainbrighton** [comment]
:lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-:-KmkAZ6HppghYkEv6Hcx:bg7igkv)*

**Comment by iainbrighton** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1, line 318 at r3](https://reviewable.io:443/reviews/powershell/xhyper-v/100#-KmesQG2HMkenXdoT77Z:-KmkAuANHq_TfYbXH8Cl:b32w0x) ([raw file](https://github.com/powershell/xhyper-v/blob/14dc7c2db866dae1870b86896c396f0bc536927e/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L318)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

darn it, missed those in earlier commit. Thanks! and done!
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/100)*

**Comment by iainbrighton** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/100)*

**Comment by bgelens** [comment]
Reviewed 1 of 2 files at r3, 1 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/100)*

**Pull request merged**
