### PR TITLE
xVMHost: added ability to enable or disable VM Live Migration

### LINKED ISSUE #155: xVMHost: Add support for enabling/disabling Live Migration
#### Details of the scenario you tried and the problem that is occurring

Currently it is not possible to enable and disable Live Migration of virtual machines by leveraging the xVMHost DSC module. This is a common feature to enable, and would be beneficial having as an option in this module.

#### Verbose logs showing the problem

Live Migration of Virtual Machines is disabled by default for Hyper-V. This can be shown by checking the VirtualMachineMigrationEnabled property in the output of Get-VMHost:

PS C:\> Get-VMHost

Name     LogicalProcessorCount MemoryCapacity(M) VirtualMachineMigrationEnabled
----     --------------------- ----------------- ------------------------------
HV01  32                    262074,203125     False

#### Suggested solution to the issue

Add a VirtualMachineMigrationEnabled property to xVMHost, which can leverage the following cmdlets to perform the logic:
Get-VMHost
Enable-VMMigration
Disable-VMMigration

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
xVMHost HyperVHostSettings
    {

        IsSingleInstance    = 'Yes'
       #VirtualMachineMigrationEnabled  <-- The property currently missing (in version 3.12.0.0) , which this issue suggests adding
        VirtualMachineMigrationAuthenticationType = 'Kerberos'
        VirtualMachineMigrationPerformanceOption = 'Compression'
        MaximumStorageMigrations = '2'
        MaximumVirtualMachineMigrations = '4'
        UseAnyNetworkForMigration = $true
        DependsOn = @('[WindowsFeature]Hyper-V','[WindowsFeature]Hyper-V-PowerShell')

    }
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2485.amd64fre.rs1_release.180827-1809
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
#### Version and build of PowerShell the target node is running

Name                           Value
----                           -----
PSVersion                      5.1.14393.2485
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2485
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.12.0.0

### PR DESCRIPTION
**Pull request by bgelens**
#### Pull Request (PR) description

Added ability to enable or disable VM Live Migration

#### This Pull Request (PR) fixes the following issues

- Fixes #155 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/158)

### CODE REVIEW

**Comment by bgelens** [comment]
ping @johlju

**Comment by johlju** [comment]
@bgelens I will focus on PR's already in review - when I have time I can come back an review this one. :) I'm back to working working with the DSC Resource Kit on my spare time.

**Comment by bgelens** [comment]
@johlju this PR is not abandoned. Considering the time it takes for review to start, maybe the time before marking stale should be increased?

**Comment by johlju** [comment]
@bgelens if the PR is labeled “needs review” it should not be marked stale. The problem is that someone (with the necessary permission) need to label the PR’s and issues.

**Comment by bgelens** [comment]
I see. And there is no assigned maintainer for this repo right? After this label is added, will the PR be closed in some time?

**Comment by johlju** [comment]
The PR will not be closed even if it labeled as stale. 
I don’t think this repo has a community maintainer, and I don’t have the permission to label any longer.

**Comment by bgelens** [comment]
I can take up this role again for this repo. Considering there currently is nobody putting in some limited effort is better than none right? (just won't be able to review my own PR)

**Comment by PlagueHO** [comment]
I'm happy to review tomorrow night if you like? @bgelens - do you still have maintainer rights to the repo?

**Comment by bgelens** [comment]
I'm not in a hurry at all so don't feel obligated :) Just was worried about the abandoned label.
I don't have the rights anymore so need to send a mail again I guess

**Comment by PlagueHO** [comment]
Doh! This was mine to review. Sorry @bgelens - will do it this weekend. Work has been a bit full on lately.

**Comment by bgelens** [comment]
No worries @PlagueHO There is no need to sacrifice your weekend on this :) I'm not in a hurry so review at your leisure

**Comment by bgelens** [comment]
@PlagueHO Thanks for reviewing! 👍  I addressed your comments and pushed a couple of additional changes after I did some more testing. Could you check these changes as well?

**Comment by bgelens** [comment]
@PlagueHO Addressed the comments. Note that ```New-InvalidOperationError``` throws a terminating error which results in ```Set-VMHost``` not being called anymore.  First the behavior was to throw non-terminating, allowing potential other settings to still be applied. I'm fine with the new behavior though. What do you think?

**Comment by bgelens** [comment]
It's already [done](https://github.com/PowerShell/DscResources/commit/ee603f332e1dd32a0a09408ef9a87f8ce923fd34) 😄 

I'll merge in a couple of days. See if anyone else have any comments if they are watching this pr.

**Comment by johlju** [comment]
Ah cool. :smile: I didn’t notice that (yet). I’m way behind in the backlog of notifications :s

**Pull request merged**
