### PR TITLE
xNetworkAdapter: Added Vlan tagging and Ip settings (Static and DHCP)

### PR DESCRIPTION
**Pull request by mcollera**
#### Pull Request (PR) description
Added support to tag a Network Adapter with a Vlan Id
Added support to configure a Network Adapter with a static IP or DHCP. B

#### This Pull Request (PR) fixes the following issues
None
#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/161)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @mcollera - looks like you've got an error in the README.MD: https://ci.appveyor.com/project/PowerShell/xhyper-v/builds/20186552#L919

**Comment by gaelcolas** [comment]
Summoning @bgelens  the great for a review. I assume he'll have plenty of free time this coming week. :)

More seriously, Ben, you're more likely to get that done quickly than myself, but if you can't I'll circle back to it in a couple of weeks or so.

**Comment by bgelens** [comment]
@gaelcolas Not something I can quickly review unfortunately. I'll see if I can find some time post summit but I'll have to fix up some kind of testing environment to check all this out

**Comment by gaelcolas** [comment]
@bgelens hit me up when you're back from summit, and we'll see if we can work together on a testing environment.

**Comment by mcollera** [comment]
I have a failed build but it is not due to any code changes I have made. Also looks like the PSSA rule that is failing has a bug in it. @bgelens @gaelcolas

**Pull request merged**
