### PR TITLE
Fix for #89: Changes in enabling / disabling dynamic memory

### PR DESCRIPTION
**Pull request by GeriOnline**
**Pull Request (PR) description**

**This Pull Request (PR) fixes the following issues:**

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated / added?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/118)

### CODE REVIEW

**Comment by bgelens** [comment]
Hi @GeriOnline. Could you start over from a new fork? I'm seeing some issues probably better resolved that way then by addressing in this PR

**Comment by GeriOnline** [comment]
Hello @bgelens. Yes, I'm already on it, because I do not know how I can solve the problems otherwise. Sorry for the inconveniences.

**Comment by bgelens** [comment]
Absolutely no problem @GeriOnline! Great you are starting your journey as a contributor :smile: and if you need any help / clarification, we are here to help.

**Comment by GeriOnline** [comment]
I will create a new pull request after restart.

**Pull request closed without merging**
