### PR TITLE
Fix bug in xVMDvdDrive with hardcoded VM Name - Fixes #85

### LINKED ISSUE #85: xVMDvdDrive hard-coded 'ADCSTest' VMName
In [xVMDvdDrive](https://github.com/PowerShell/xHyper-V/blob/dev/DSCResources/MSFT_xVMDvdDrive/MSFT_xVMDvdDrive.psm1#L395-L396) the `VMName` parameter is hard-coded to `ADCSTest`. This makes it kind of hard to attach an ISO to any other machine 😜.

### PR DESCRIPTION
**Pull request by PlagueHO**
* Fix bug in xVMDvdDrive with hardcoded VM Name.
* Corrected Markdown rule violations in Readme.md.

I also updated the unit tests to prevent regression.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xhyper-v/86)

### CODE REVIEW

**Comment by iainbrighton** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/86#-:-Kgn8-TjLKiH3BotkZ9v:bnfp4nl)*

**Comment by iainbrighton** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/86)*

**Comment by PlagueHO** [comment]
@kwirkykat - this PR fixes a significant bug (my bug). I'm not sure who is an administrator on this repo (so tagging you). Any chance this could be merged before next resource kit release? Thank you for putting up with my requests :grin:

**Comment by PlagueHO** [comment]
@mbreakey3 - any chance of getting a merge on this one? :grin:

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xhyper-v/86#-:-KiX-pgRKcOaVw9g1FHY:bnfp4nl)*

**Pull request merged**
